# Welcome to Jekyll!

# Website settings
title: Dr.Priya Rao
description: My blog
keywords: 
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://drpriyarao.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:8000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Dr.Priya Rao  # Be used at blog posts' author.
  first_name: Priya  # Be used at index page about me section.
  last_name: Rao  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: drpriyarao  # Leave blank if you don't have now
  linkedin_id: # Leave blank if you don't have now
  facebook_username: priya.rao.311       # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email: drpriyavrao5@gmail.com  # Leave blank if you don't have now
  cv:   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Hello, I'm Dr. Priya Rao, dental surgeon and implantologist practising in Virar since 1995. My special interests are Root canals, Esthetic Dentistry and Full mouth Rehabilitations. Enabling and enhancing Happy smiles is my passion :) For this I keep upgrading my skills. And when I m not pursuing this passion, you will find me either writing, painting, reading or dabbling in photography. And yes this may sound clichéd but is 100% true that I do what I love and love what I do :) # comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: Priya Rao

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id : UA-109230366-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
